//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by d2-i18n-generate.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import i18n from '@dhis2/d2-i18n'

import enTranslations from './en/translations.json'
import frTranslations from './fr/translations.json'
import i18n_module_arTranslations from './i18n_module_ar/translations.json'
import i18n_module_ar_IQTranslations from './i18n_module_ar_IQ/translations.json'
import i18n_module_ckbTranslations from './i18n_module_ckb/translations.json'
import i18n_module_csTranslations from './i18n_module_cs/translations.json'
import i18n_module_daTranslations from './i18n_module_da/translations.json'
import i18n_module_enTranslations from './i18n_module_en/translations.json'
import i18n_module_esTranslations from './i18n_module_es/translations.json'
import i18n_module_frTranslations from './i18n_module_fr/translations.json'
import i18n_module_idTranslations from './i18n_module_id/translations.json'
import i18n_module_kmTranslations from './i18n_module_km/translations.json'
import i18n_module_loTranslations from './i18n_module_lo/translations.json'
import i18n_module_myTranslations from './i18n_module_my/translations.json'
import i18n_module_nbTranslations from './i18n_module_nb/translations.json'
import i18n_module_nlTranslations from './i18n_module_nl/translations.json'
import i18n_module_prsTranslations from './i18n_module_prs/translations.json'
import i18n_module_psTranslations from './i18n_module_ps/translations.json'
import i18n_module_ptTranslations from './i18n_module_pt/translations.json'
import i18n_module_pt_BRTranslations from './i18n_module_pt_BR/translations.json'
import i18n_module_ruTranslations from './i18n_module_ru/translations.json'
import i18n_module_svTranslations from './i18n_module_sv/translations.json'
import i18n_module_tetTranslations from './i18n_module_tet/translations.json'
import i18n_module_tgTranslations from './i18n_module_tg/translations.json'
import i18n_module_ukTranslations from './i18n_module_uk/translations.json'
import i18n_module_urTranslations from './i18n_module_ur/translations.json'
import i18n_module_uzTranslations from './i18n_module_uz/translations.json'
import i18n_module_uz_CyrlTranslations from './i18n_module_uz_Cyrl/translations.json'
import i18n_module_uz_LatnTranslations from './i18n_module_uz_Latn/translations.json'
import i18n_module_viTranslations from './i18n_module_vi/translations.json'
import i18n_module_zhTranslations from './i18n_module_zh/translations.json'
import i18n_module_zh_CNTranslations from './i18n_module_zh_CN/translations.json'

const namespace = 'default'
i18n.addResources('en', namespace, enTranslations)
i18n.addResources('fr', namespace, frTranslations)
i18n.addResources('i18n_module_ar', namespace, i18n_module_arTranslations)
i18n.addResources('i18n_module_ar_IQ', namespace, i18n_module_ar_IQTranslations)
i18n.addResources('i18n_module_ckb', namespace, i18n_module_ckbTranslations)
i18n.addResources('i18n_module_cs', namespace, i18n_module_csTranslations)
i18n.addResources('i18n_module_da', namespace, i18n_module_daTranslations)
i18n.addResources('i18n_module_en', namespace, i18n_module_enTranslations)
i18n.addResources('i18n_module_es', namespace, i18n_module_esTranslations)
i18n.addResources('i18n_module_fr', namespace, i18n_module_frTranslations)
i18n.addResources('i18n_module_id', namespace, i18n_module_idTranslations)
i18n.addResources('i18n_module_km', namespace, i18n_module_kmTranslations)
i18n.addResources('i18n_module_lo', namespace, i18n_module_loTranslations)
i18n.addResources('i18n_module_my', namespace, i18n_module_myTranslations)
i18n.addResources('i18n_module_nb', namespace, i18n_module_nbTranslations)
i18n.addResources('i18n_module_nl', namespace, i18n_module_nlTranslations)
i18n.addResources('i18n_module_prs', namespace, i18n_module_prsTranslations)
i18n.addResources('i18n_module_ps', namespace, i18n_module_psTranslations)
i18n.addResources('i18n_module_pt', namespace, i18n_module_ptTranslations)
i18n.addResources('i18n_module_pt_BR', namespace, i18n_module_pt_BRTranslations)
i18n.addResources('i18n_module_ru', namespace, i18n_module_ruTranslations)
i18n.addResources('i18n_module_sv', namespace, i18n_module_svTranslations)
i18n.addResources('i18n_module_tet', namespace, i18n_module_tetTranslations)
i18n.addResources('i18n_module_tg', namespace, i18n_module_tgTranslations)
i18n.addResources('i18n_module_uk', namespace, i18n_module_ukTranslations)
i18n.addResources('i18n_module_ur', namespace, i18n_module_urTranslations)
i18n.addResources('i18n_module_uz', namespace, i18n_module_uzTranslations)
i18n.addResources('i18n_module_uz_Cyrl', namespace, i18n_module_uz_CyrlTranslations)
i18n.addResources('i18n_module_uz_Latn', namespace, i18n_module_uz_LatnTranslations)
i18n.addResources('i18n_module_vi', namespace, i18n_module_viTranslations)
i18n.addResources('i18n_module_zh', namespace, i18n_module_zhTranslations)
i18n.addResources('i18n_module_zh_CN', namespace, i18n_module_zh_CNTranslations)

export default i18n
