const dataSetByOrgUnitSchemaDefinition = {
    klass: 'org.hisp.dhis.dataset.DataSet',
    shareable: true,
    translatable: true,
    metadata: true,
    identifiableObject: true,
    apiEndpoint: 'http://localhost:8080/dhis/api/29/dataSets',
    plural: 'dataSets',
    displayName: 'Data Set By Organisation Unit',
    name: 'dataSetByOrgUnit',
    singular: 'dataSetByOrgUnit',
    authorities: [
        {
            type: 'CREATE_PUBLIC',
            authorities: [
                'F_SYSTEM_SETTING',
            ],
        },
        {
            type: 'CREATE_PRIVATE',
            authorities: [
                'F_SYSTEM_SETTING',
            ],
        },
        {
            type: 'DELETE',
            authorities: [
                'F_SYSTEM_SETTING',
            ],
        },
    ],
    properties: [
        {
            owner: true,
            ordered: false,
            collection: false,
            required: false,
            writable: true,
            embeddedObject: false,
            propertyType: 'REFERENCE',
            unique: false,
            name: 'dataEntryForm',
            href: 'http://localhost:8080/dhis/api/schemas/dataEntryForm',
            persisted: true,
        },
        {
            owner: true,
            ordered: false,
            collection: false,
            required: false,
            writable: true,
            embeddedObject: false,
            propertyType: 'BOOLEAN',
            unique: false,
            name: 'validCompleteOnly',
            persisted: true,
        },
        {
            owner: true,
            ordered: false,
            max: 1.7976931348623157e+308,
            collection: true,
            itemPropertyType: 'COMPLEX',
            required: false,
            writable: true,
            collectionName: 'dataSetElements',
            min: 0,
            embeddedObject: true,
            propertyType: 'COLLECTION',
            unique: false,
            name: 'dataSetElement',
            persisted: true,
        },
        {
            owner: true,
            ordered: false,
            max: 8,
            collection: false,
            required: false,
            writable: true,
            min: 8,
            embeddedObject: false,
            propertyType: 'TEXT',
            unique: false,
            name: 'publicAccess',
            persisted: true,
        },
        {
            owner: true,
            ordered: false,
            collection: false,
            required: false,
            writable: true,
            embeddedObject: false,
            propertyType: 'BOOLEAN',
            unique: false,
            name: 'skipOffline',
            persisted: true,
        },
        {
            owner: true,
            ordered: false,
            collection: false,
            required: false,
            writable: true,
            embeddedObject: false,
            propertyType: 'BOOLEAN',
            unique: false,
            name: 'compulsoryFieldsCompleteOnly',
            persisted: true,
        },
        {
            owner: true,
            ordered: false,
            collection: false,
            required: false,
            writable: true,
            embeddedObject: false,
            propertyType: 'DATE',
            unique: false,
            name: 'lastUpdated',
            persisted: true,
        },
        {
            owner: true,
            ordered: false,
            collection: false,
            required: true,
            writable: true,
            embeddedObject: false,
            propertyType: 'REFERENCE',
            unique: false,
            name: 'categoryCombo',
            href: 'http://localhost:8080/dhis/api/schemas/categoryCombo',
            persisted: true,
        },
        {
            owner: true,
            ordered: false,
            max: 1.7976931348623157e+308,
            collection: true,
            itemPropertyType: 'COMPLEX',
            required: false,
            writable: true,
            collectionName: 'translations',
            min: 0,
            embeddedObject: false,
            propertyType: 'COLLECTION',
            unique: false,
            name: 'translation',
            persisted: true,
        },
        {
            owner: true,
            ordered: false,
            max: 1.7976931348623157e+308,
            collection: true,
            itemPropertyType: 'COMPLEX',
            required: false,
            writable: true,
            collectionName: 'dataInputPeriods',
            min: 0,
            embeddedObject: true,
            propertyType: 'COLLECTION',
            unique: false,
            name: 'dataInputPeriods',
            persisted: true,
        },
        {
            owner: true,
            ordered: false,
            max: 11,
            collection: false,
            required: false,
            writable: true,
            min: 11,
            embeddedObject: false,
            propertyType: 'IDENTIFIER',
            unique: true,
            name: 'id',
            persisted: true,
        },
        {
            owner: false,
            ordered: false,
            max: 1.7976931348623157e+308,
            collection: false,
            required: false,
            writable: true,
            min: 0,
            embeddedObject: false,
            propertyType: 'URL',
            unique: false,
            name: 'href',
            persisted: false,
        },
        {
            owner: false,
            ordered: false,
            max: 1.7976931348623157e+308,
            collection: true,
            itemPropertyType: 'REFERENCE',
            required: false,
            writable: true,
            collectionName: 'interpretations',
            min: 0,
            embeddedObject: false,
            propertyType: 'COLLECTION',
            unique: false,
            name: 'interpretation',
            href: 'http://localhost:8080/dhis/api/schemas/interpretation',
            persisted: true,
        },
        {
            owner: false,
            ordered: false,
            max: 2147483647,
            collection: false,
            required: false,
            writable: true,
            min: 0,
            embeddedObject: false,
            propertyType: 'TEXT',
            unique: false,
            name: 'displayDescription',
            persisted: false,
        },
        {
            owner: true,
            ordered: false,
            collection: false,
            required: false,
            writable: true,
            embeddedObject: false,
            propertyType: 'REFERENCE',
            unique: false,
            name: 'lastUpdatedBy',
            href: 'http://localhost:8080/dhis/api/schemas/user',
            persisted: true,
        },
        {
            owner: false,
            ordered: false,
            collection: false,
            required: false,
            writable: false,
            embeddedObject: false,
            propertyType: 'CONSTANT',
            unique: false,
            name: 'formType',
            persisted: false,
            constants: [
                'DEFAULT',
                'CUSTOM',
                'SECTION',
                'SECTION_MULTIORG'
            ],
        },
        {
            owner: true,
            ordered: false,
            max: 1.7976931348623157e+308,
            collection: true,
            itemPropertyType: 'COMPLEX',
            required: false,
            writable: true,
            collectionName: 'userGroupAccesses',
            min: 0,
            embeddedObject: true,
            propertyType: 'COLLECTION',
            unique: false,
            name: 'userGroupAccess',
            persisted: true,
        },
        {
            owner: true,
            ordered: false,
            collection: false,
            required: false,
            writable: true,
            embeddedObject: false,
            propertyType: 'REFERENCE',
            unique: false,
            name: 'workflow',
            href: 'http://localhost:8080/dhis/api/schemas/dataApprovalWorkflow',
            persisted: true,
        },
        {
            owner: true,
            ordered: false,
            collection: false,
            required: false,
            writable: true,
            embeddedObject: false,
            propertyType: 'DATE',
            unique: false,
            name: 'created',
            persisted: true,
        },
        {
            owner: true,
            ordered: false,
            max: 1.7976931348623157e+308,
            collection: true,
            itemPropertyType: 'COMPLEX',
            required: false,
            writable: true,
            collectionName: 'attributeValues',
            min: 0,
            embeddedObject: false,
            propertyType: 'COLLECTION',
            unique: false,
            name: 'attributeValue',
            persisted: true,
        },
        {
            owner: true,
            ordered: false,
            max: 1.7976931348623157e+308,
            collection: true,
            itemPropertyType: 'REFERENCE',
            required: false,
            writable: true,
            collectionName: 'indicators',
            min: 0,
            embeddedObject: false,
            propertyType: 'COLLECTION',
            unique: false,
            name: 'indicator',
            href: 'http://localhost:8080/dhis/api/schemas/indicator',
            persisted: true,
        },
        {
            owner: true,
            ordered: false,
            max: 2147483647,
            collection: false,
            required: false,
            writable: true,
            min: 0,
            embeddedObject: false,
            propertyType: 'INTEGER',
            unique: false,
            name: 'version',
            persisted: true,
        },
        {
            owner: false,
            ordered: false,
            max: 1.7976931348623157e+308,
            collection: true,
            itemPropertyType: 'REFERENCE',
            required: false,
            writable: true,
            collectionName: 'sections',
            min: 0,
            embeddedObject: false,
            propertyType: 'COLLECTION',
            unique: false,
            name: 'section',
            href: 'http://localhost:8080/dhis/api/schemas/section',
            persisted: true,
        },
        {
            owner: true,
            ordered: false,
            max: 2147483647,
            collection: false,
            required: false,
            writable: true,
            min: 0,
            embeddedObject: false,
            propertyType: 'INTEGER',
            unique: false,
            name: 'timelyDays',
            persisted: true,
        },
        {
            owner: true,
            ordered: false,
            max: 1.7976931348623157e+308,
            collection: true,
            itemPropertyType: 'COMPLEX',
            required: false,
            writable: true,
            collectionName: 'userAccesses',
            min: 0,
            embeddedObject: true,
            propertyType: 'COLLECTION',
            unique: false,
            name: 'userAccess',
            persisted: true,
        },
        {
            owner: true,
            ordered: false,
            translationKey: 'NAME',
            max: 230,
            collection: false,
            required: true,
            writable: true,
            min: 1,
            embeddedObject: false,
            propertyType: 'TEXT',
            unique: false,
            name: 'name',
            persisted: true,
        },
        {
            owner: true,
            ordered: true,
            max: 1.7976931348623157e+308,
            collection: true,
            itemPropertyType: 'REFERENCE',
            required: false,
            writable: true,
            collectionName: 'legendSets',
            min: 0,
            embeddedObject: false,
            propertyType: 'COLLECTION',
            unique: false,
            name: 'legendSets',
            href: 'http://localhost:8080/dhis/api/schemas/legendSet',
            persisted: true,
        },
        {
            owner: true,
            ordered: false,
            max: 255,
            collection: false,
            required: false,
            writable: true,
            min: 0,
            embeddedObject: false,
            propertyType: 'COMPLEX',
            unique: false,
            name: 'style',
            persisted: true,
        },
        {
            owner: true,
            ordered: false,
            collection: false,
            required: false,
            writable: true,
            embeddedObject: false,
            propertyType: 'REFERENCE',
            unique: false,
            name: 'notificationRecipients',
            href: 'http://localhost:8080/dhis/api/schemas/userGroup',
            persisted: true,
        },
        {
            owner: true,
            ordered: false,
            translationKey: 'SHORT_NAME',
            max: 50,
            collection: false,
            required: false,
            writable: true,
            min: 1,
            embeddedObject: false,
            propertyType: 'TEXT',
            unique: false,
            name: 'shortName',
            persisted: true,
        },
        {
            owner: false,
            ordered: false,
            collection: false,
            required: false,
            writable: false,
            embeddedObject: false,
            propertyType: 'BOOLEAN',
            unique: false,
            name: 'favorite',
            persisted: false,
        },
        {
            owner: false,
            ordered: false,
            collection: false,
            required: false,
            writable: true,
            embeddedObject: false,
            propertyType: 'CONSTANT',
            unique: false,
            name: 'dimensionItemType',
            persisted: false,
            constants: [
                'DATA_ELEMENT',
                'DATA_ELEMENT_OPERAND',
                'INDICATOR',
                'REPORTING_RATE',
                'PROGRAM_DATA_ELEMENT',
                'PROGRAM_ATTRIBUTE',
                'PROGRAM_INDICATOR',
                'PERIOD',
                'ORGANISATION_UNIT',
                'CATEGORY_OPTION',
                'OPTION_GROUP',
                'DATA_ELEMENT_GROUP',
                'ORGANISATION_UNIT_GROUP',
                'CATEGORY_OPTION_GROUP'
            ],
        },
        {
            owner: false,
            ordered: false,
            max: 1.7976931348623157e+308,
            collection: true,
            itemPropertyType: 'TEXT',
            required: false,
            writable: true,
            collectionName: 'favorites',
            min: 0,
            embeddedObject: false,
            propertyType: 'COLLECTION',
            unique: false,
            name: 'favorite',
            persisted: false,
        },
        {
            owner: false,
            ordered: false,
            collection: false,
            required: false,
            writable: true,
            embeddedObject: false,
            propertyType: 'CONSTANT',
            unique: false,
            name: 'aggregationType',
            persisted: false,
            constants: [
                'SUM',
                'AVERAGE',
                'AVERAGE_SUM_ORG_UNIT',
                'LAST',
                'LAST_AVERAGE_ORG_UNIT',
                'COUNT',
                'STDDEV',
                'VARIANCE',
                'MIN',
                'MAX',
                'NONE',
                'CUSTOM',
                'DEFAULT'
            ],
        },
        {
            owner: true,
            ordered: false,
            max: 50,
            collection: false,
            required: false,
            writable: true,
            min: 0,
            embeddedObject: false,
            propertyType: 'IDENTIFIER',
            unique: true,
            name: 'code',
            persisted: true,
        },
        {
            owner: false,
            ordered: false,
            max: 1.7976931348623157e+308,
            collection: false,
            required: false,
            writable: true,
            min: 0,
            embeddedObject: false,
            propertyType: 'COMPLEX',
            unique: false,
            name: 'access',
            persisted: false,
        },
        {
            owner: true,
            ordered: false,
            collection: false,
            required: false,
            writable: true,
            embeddedObject: false,
            propertyType: 'BOOLEAN',
            unique: false,
            name: 'dataElementDecoration',
            persisted: true,
        },
        {
            owner: false,
            ordered: false,
            max: 2147483647,
            collection: false,
            required: false,
            writable: true,
            min: 0,
            embeddedObject: false,
            propertyType: 'TEXT',
            unique: false,
            name: 'displayName',
            persisted: false,
        },
        {
            owner: true,
            ordered: false,
            collection: false,
            required: false,
            writable: true,
            embeddedObject: false,
            propertyType: 'BOOLEAN',
            unique: false,
            name: 'notifyCompletingUser',
            persisted: true,
        },
        {
            owner: true,
            ordered: false,
            collection: false,
            required: false,
            writable: true,
            embeddedObject: false,
            propertyType: 'BOOLEAN',
            unique: false,
            name: 'noValueRequiresComment',
            persisted: true,
        },
        {
            owner: true,
            ordered: false,
            max: 1.7976931348623157e+308,
            collection: true,
            itemPropertyType: 'REFERENCE',
            required: false,
            writable: true,
            collectionName: 'compulsoryDataElementOperands',
            min: 0,
            embeddedObject: true,
            propertyType: 'COLLECTION',
            unique: false,
            name: 'compulsoryDataElementOperand',
            href: 'http://localhost:8080/dhis/api/schemas/dataElementOperand',
            persisted: true,
        },
        {
            owner: true,
            ordered: false,
            translationKey: 'DESCRIPTION',
            max: 2147483647,
            collection: false,
            required: false,
            writable: true,
            min: 1,
            embeddedObject: false,
            propertyType: 'TEXT',
            unique: false,
            name: 'description',
            persisted: true,
        },
        {
            owner: false,
            ordered: false,
            max: 2147483647,
            collection: false,
            required: false,
            writable: true,
            min: 0,
            embeddedObject: false,
            propertyType: 'TEXT',
            unique: false,
            name: 'displayShortName',
            persisted: false,
        },
        {
            owner: false,
            ordered: false,
            collection: false,
            required: false,
            writable: true,
            embeddedObject: false,
            propertyType: 'BOOLEAN',
            unique: false,
            name: 'externalAccess',
            persisted: false,
        },
        {
            owner: true,
            ordered: false,
            collection: false,
            required: false,
            writable: true,
            embeddedObject: false,
            propertyType: 'BOOLEAN',
            unique: false,
            name: 'fieldCombinationRequired',
            persisted: true,
        },
        {
            owner: true,
            ordered: false,
            translationKey: 'FORM_NAME',
            max: 2147483647,
            collection: false,
            required: false,
            writable: true,
            min: 0,
            embeddedObject: false,
            propertyType: 'TEXT',
            unique: false,
            name: 'formName',
            persisted: true,
        },
        {
            owner: true,
            ordered: false,
            max: 1.7976931348623157e+308,
            collection: true,
            itemPropertyType: 'REFERENCE',
            required: false,
            writable: true,
            collectionName: 'organisationUnits',
            min: 0,
            embeddedObject: false,
            propertyType: 'COLLECTION',
            unique: false,
            name: 'organisationUnit',
            href: 'http://localhost:8080/dhis/api/schemas/organisationUnit',
            persisted: true,
        },
        {
            owner: true,
            ordered: false,
            collection: false,
            required: false,
            writable: true,
            embeddedObject: false,
            propertyType: 'BOOLEAN',
            unique: false,
            name: 'renderHorizontally',
            persisted: true,
        },
        {
            owner: true,
            ordered: false,
            collection: false,
            required: false,
            writable: true,
            embeddedObject: false,
            propertyType: 'BOOLEAN',
            unique: false,
            name: 'renderAsTabs',
            persisted: true,
        },
        {
            owner: false,
            ordered: false,
            collection: false,
            required: false,
            writable: false,
            embeddedObject: false,
            propertyType: 'TEXT',
            unique: false,
            name: 'dimensionItem',
            persisted: false,
        },
        {
            owner: true,
            ordered: false,
            collection: false,
            required: true,
            writable: true,
            embeddedObject: false,
            propertyType: 'BOOLEAN',
            unique: false,
            name: 'mobile',
            persisted: true,
        },
        {
            owner: true,
            ordered: false,
            max: 255,
            collection: false,
            required: true,
            writable: true,
            min: 0,
            embeddedObject: false,
            propertyType: 'TEXT',
            unique: false,
            name: 'periodType',
            persisted: true,
        },
        {
            owner: false,
            ordered: false,
            collection: false,
            required: false,
            writable: false,
            embeddedObject: false,
            propertyType: 'REFERENCE',
            unique: false,
            name: 'legendSet',
            href: 'http://localhost:8080/dhis/api/schemas/legendSet',
            persisted: false,
        },
        {
            owner: true,
            ordered: false,
            max: 2147483647,
            collection: false,
            required: false,
            writable: true,
            min: 0,
            embeddedObject: false,
            propertyType: 'INTEGER',
            unique: false,
            name: 'openFuturePeriods',
            persisted: true,
        },
        {
            owner: true,
            ordered: false,
            max: 2147483647,
            collection: false,
            required: false,
            writable: true,
            min: -2147483648,
            embeddedObject: false,
            propertyType: 'INTEGER',
            unique: false,
            name: 'expiryDays',
            persisted: true,
        },
        {
            owner: true,
            ordered: false,
            collection: false,
            required: false,
            writable: true,
            embeddedObject: false,
            propertyType: 'REFERENCE',
            unique: false,
            name: 'user',
            href: 'http://localhost:8080/dhis/api/schemas/user',
            persisted: true,
        },
        {
            owner: true,
            ordered: false,
            max: 1.7976931348623157e+308,
            collection: true,
            itemPropertyType: 'REFERENCE',
            required: false,
            writable: true,
            collectionName: 'greyedFields',
            min: 0,
            embeddedObject: true,
            propertyType: 'COLLECTION',
            unique: false,
            name: 'greyedField',
            href: 'http://localhost:8080/dhis/api/schemas/dataElementOperand',
            persisted: true,
        },
    ],
};

export default dataSetByOrgUnitSchemaDefinition;
