/*const dataSetByOrgUnitSchemaAttributes = [
    {
        lastUpdated: '2018-08-18T20:58:10.808',
        id: 'y1kjuGaExZb',
        href: 'http://localhost:8080/dhis/api/29/attributes/y1kjuGaExZb',
        created: '2018-06-25T17:41:04.734',
        name: 'ERR Analysis',
        shortName: 'ERR Analysis',
        code: 'ATT_DS_ERR_ANALYSIS',
        indicatorAttribute: false,
        indicatorGroupAttribute: false,
        publicAccess: 'r-------',
        userGroupAttribute: false,
        dataElementAttribute: false,
        constantAttribute: false,
        valueType: 'TRUE_ONLY',
        categoryOptionAttribute: false,
        optionSetAttribute: false,
        sqlViewAttribute: false,
        legendSetAttribute: false,
        trackedEntityAttributeAttribute: false,
        organisationUnitAttribute: false,
        dataSetAttribute: true,
        documentAttribute: false,
        unique: false,
        validationRuleGroupAttribute: false,
        favorite: false,
        dataElementGroupAttribute: false,
        sectionAttribute: false,
        trackedEntityTypeAttribute: false,
        userAttribute: false,
        displayName: 'ERR Analysis',
        mandatory: false,
        categoryOptionGroupAttribute: false,
        displayShortName: 'ERR Analysis',
        externalAccess: false,
        programStageAttribute: false,
        programAttribute: false,
        categoryAttribute: false,
        categoryOptionComboAttribute: false,
        categoryOptionGroupSetAttribute: false,
        validationRuleAttribute: false,
        programIndicatorAttribute: false,
        organisationUnitGroupAttribute: false,
        dataElementGroupSetAttribute: false,
        organisationUnitGroupSetAttribute: false,
        optionAttribute: false,
        lastUpdatedBy: {
            id: 'cZBTIqGja83'
        },
        access: {
            read: true,
            update: true,
            externalize: true,
            delete: true,
            write: true,
            manage: true
        },
        user: {
            id: 'cZBTIqGja83'
        },
        translations: [],
        userGroupAccesses: [],
        attributeValues: [],
        userAccesses: [],
        favorites: []
    },
    {
        lastUpdated: '2018-08-18T20:58:10.809',
        id: 'wtbDO1ZyE4e',
        href: 'http://localhost:8080/dhis/api/29/attributes/wtbDO1ZyE4e',
        created: '2016-11-15T10:09:56.422',
        name: 'eTick Register',
        shortName: 'eTick Register',
        code: 'ATT_DS_ETICK_REG',
        indicatorAttribute: false,
        indicatorGroupAttribute: false,
        publicAccess: 'r-------',
        userGroupAttribute: false,
        dataElementAttribute: false,
        constantAttribute: false,
        valueType: 'BOOLEAN',
        categoryOptionAttribute: false,
        optionSetAttribute: false,
        displayDescription: 'Whether a data element is used in the eTick Register',
        sqlViewAttribute: false,
        legendSetAttribute: false,
        trackedEntityAttributeAttribute: false,
        organisationUnitAttribute: false,
        dataSetAttribute: true,
        documentAttribute: false,
        unique: false,
        validationRuleGroupAttribute: false,
        favorite: false,
        dataElementGroupAttribute: false,
        sectionAttribute: false,
        trackedEntityTypeAttribute: false,
        userAttribute: false,
        displayName: 'eTick Register',
        description: 'Whether a data element is used in the eTick Register',
        mandatory: true,
        categoryOptionGroupAttribute: false,
        displayShortName: 'eTick Register',
        externalAccess: false,
        programStageAttribute: false,
        programAttribute: false,
        categoryAttribute: false,
        categoryOptionComboAttribute: false,
        categoryOptionGroupSetAttribute: false,
        validationRuleAttribute: false,
        programIndicatorAttribute: false,
        organisationUnitGroupAttribute: false,
        dataElementGroupSetAttribute: false,
        organisationUnitGroupSetAttribute: false,
        optionAttribute: false,
        lastUpdatedBy: {
            id: 'cZBTIqGja83'
        },
        access: {
            read: true,
            update: true,
            externalize: true,
            delete: true,
            write: true,
            manage: true
        },
        user: {
            id: 'cZBTIqGja83'
        },
        translations: [],
        userGroupAccesses: [],
        attributeValues: [],
        userAccesses: [],
        favorites: []
    }
];*/

const dataSetByOrgUnitSchemaAttributes = [];

export default dataSetByOrgUnitSchemaAttributes;
