const LISTING = 'LISTING';
const SEQUENTIAL = 'SEQUENTIAL';
const MATRIX = 'MATRIX';
const DEFAULT = 'DEFAULT';
const DROPDOWN = 'DROPDOWN';
const VERTICAL_RADIOBUTTONS = 'VERTICAL_RADIOBUTTONS';
const HORIZONTAL_RADIOBUTTONS = 'HORIZONTAL_RADIOBUTTONS';
const VERTICAL_CHECKBOXES = 'VERTICAL_CHECKBOXES';
const HORIZONTAL_CHECKBOXES = 'HORIZONTAL_CHECKBOXES';
const SHARED_HEADER_RADIOBUTTONS = 'SHARED_HEADER_RADIOBUTTONS';
const ICONS_AS_BUTTONS = 'ICONS_AS_BUTTONS';
const SPINNER = 'SPINNER';
const ICON = 'ICON';
const TOGGLE = 'TOGGLE';
const VALUE = 'VALUE';
const SLIDER = 'SLIDER';
const LINEAR_SCALE = 'LINEAR_SCALE';

export const PROGRAM_STAGE_SECTION_RENDER_TYPES = [
    LISTING,
    SEQUENTIAL,
    MATRIX,
];

export const DEFAULT_PROGRAM_STAGE_RENDER_TYPE = LISTING;

export const DATA_ELEMENT_AND_TRACKED_ENTITY_ATTRIBUTE_RENDER_TYPES = [
    DEFAULT,
    DROPDOWN,
    VERTICAL_RADIOBUTTONS,
    HORIZONTAL_RADIOBUTTONS,
    VERTICAL_CHECKBOXES,
    HORIZONTAL_CHECKBOXES,
    SHARED_HEADER_RADIOBUTTONS,
    ICONS_AS_BUTTONS,
    SPINNER,
    ICON,
    TOGGLE,
    VALUE,
    SLIDER,
    LINEAR_SCALE,
];
