import '@dhis2/d2-ui-core/css/Pagination.css'
import '@dhis2/d2-ui-core/css/Table.css'

import './ColorPickers/ColorPickers.css'
import './EditModel/EditDataEntryForm.css'
import './EditModel/EditDataEntryFormProgramStage.css'
import './EditModel/EditModel.css'
import './HeaderBar/HeaderBar.css'
import './IconPicker/IconPicker.css'
import './List/DetailsBox.css'
import './List/List.css'
import './SideBar/SideBar.css'
import './SqlView/SqlView.css'
import './maintenance.css'
