const programRuleFunctions = [
    'd2:ceil( <number> )',
    'd2:floor( <number> )',
    'd2:round( <number> )',
    'd2:modulus( <number> , <number> )',
    'd2:zing( <number> )',
    'd2:oizp( <number> )',
    'd2:concatenate( <object>, <object>, ...)',
    'd2:daysBetween( <date>, <date> )',
    'd2:weeksBetween( <date>, <date> )',
    'd2:monthsBetween( <date>, <date> )',
    'd2:yearsBetween( <date>, <date> )',
    'd2:addDays( <date>, <number> )',
    'd2:count( <sourcefield> )',
    'd2:countIfValue( <sourcefield>, <text> )',
    'd2:countIfZeroPos( <sourcefield> )',
    'd2:hasValue( <sourcefield> )',
    'd2:zpvc( <object>, <object>, ...)',
    'd2:validatePattern( <text>, <regex> )',
    'd2:left( <text>, <number> )',
    'd2:right( <text>, <number> )',
    'd2:substring( <text>, <number>, <number> )',
    'd2:split( <text>, <text>, <number> )',
    'd2:length( <text> )',
    'd2:inOrgUnitGroup( <orgunit_group_code> )',
    'd2:hasUserRole( <user_role> )',
    'd2:zScoreWFA( <ageInMonth>, <weight>, <gender> )',
    'd2:zScoreHFA( <ageInMonth>, <height>, <gender> )',
    'd2:zScoreWFH( <height>, <weight>, <gender> )',
];

export default programRuleFunctions;
